### ISSUE TITLE
Logo image should be replaceable

### ISSUE THREAD

**Issue by abhir9** [LoginRadius/egnature#1]

**Comment by baniksudipto** [comment]
is this issue still open? I tested on the master branch and seems like the logo image is replaceable.

**Comment by abhir9** [comment]
Yes this is still open, currently profile image is replaceable but not logo image (it should behave same like profile image)

**Comment by anoopmsivadas** [comment]
managed to fix this one. I hope its fine if i create the pull request on Oct 1.

**Comment by abhir9** [comment]
@anoopmsivadas 
OK, but its behavior should be consistent with different shapes of images.
if you are already on this let me know if you wanted to assigned to yourself

**Comment by anoopmsivadas** [comment]
@abhir9 yeah, please assign it to me

**Comment by anoopmsivadas** [comment]
![image](https://user-images.githubusercontent.com/46913894/94517743-37ad4280-0246-11eb-9b1a-4bb8582ef7f5.png)

@abhir9
