### ISSUE TITLE
vulnerabilities needs to be fix

### ISSUE THREAD

**Issue by abhir9** [LoginRadius/egnature#2]

**Comment by daniloff200** [comment]
hey @abhir9 
What kind of vulnerabilities do you mean?
Is it an npm outdated versions, or, you mean some warnings, which appears in console after the build?

**Comment by abhir9** [comment]
@daniloff200 Yes , it is related to npm outdated versions.

**Comment by MHFarooqui** [comment]
hey! can I take this, if no one is working on this?

**Comment by abhir9** [comment]
@MHFarooqui I believe not yet, you can continue on this.

**Comment by MHFarooqui** [comment]
cool! I'll update all the dependencies  to the latest available  versions and will create a pr on 1st Oct if that's okay?. also can you please assign this to me.

**Comment by abhir9** [comment]
@MHFarooqui  Assigned to you now , let me know in case of improbability ill unassigned .

**Comment by MHFarooqui** [comment]
@abhir9 thanks!

**Comment by vyasriday** [comment]
Hey @MHFarooqui  Thanks for contributing to LoginRadius Open Source.  As part of hacktoberfest, LoginRadius is also giving free swags and goodies to its contributors. Please check out our [Hacktoberfest Page](https://www.loginradius.com/engineering/page/hacktoberfest2020) and fill the form mentioned there to become eligible for free swags. :)

**Comment by MHFarooqui** [comment]
Thanks @vyasriday , submitted the form. Looking  forward to awesome swags ☺
