### ISSUE TITLE
While edit fields click on done, keep open edit field (should be closed)

### ISSUE THREAD

**Issue by abhir9** [LoginRadius/egnature#3]

**Comment by daniloff200** [comment]
Please, assign this to me :)
Would like to fix that

**Comment by abhir9** [comment]
![image](https://user-images.githubusercontent.com/15150970/94358848-7960b080-00c1-11eb-885b-f53f832c5006.png)

on hover still edit icon is visible, need to fix that as well.

**Comment by sohamsshah** [comment]
@abhir9 Can I work on this issue? Or is there any other feature you would assign me for? Open and excited to contribute to loginRadius

**Comment by daniloff200** [comment]
Got you @abhir9 , gonna fix that today
